### ISSUE TITLE
Class 1, Project 3: Some operators missing

### ISSUE THREAD

**Issue by fosterbrereton** [droidsb/General-Coding#1]
Nice job on the operators so far. Please make sure you use all of the following:
- `===`
- `!=`
- `>`
- `<`
- `<=`
- `>=`

**Comment by droidsb** [comment]
Thanks, Where am I supposed to put the <= and >=?

**Comment by fosterbrereton** [comment]
I'd say you can put them pretty much anywhere. It's ok if two values match on more than one if statement. It's more an exercise to get you experience- I'm not looking for specific output.

**Comment by droidsb** [comment]
Ok I added all of the commands and pushed them to github

**Comment by fosterbrereton** [comment]
Great! I'll close out this issue.
